"""add note ownership and timestamps

Revision ID: 50531f92702a
Revises: 3393f5495378
Create Date: 2026-07-12 21:16:52.923107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50531f92702a'
down_revision: Union[str, Sequence[str], None] = '3393f5495378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('notes', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('notes', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('notes', sa.Column('updated_at', sa.DateTime(), nullable=True))

    op.execute(
        "UPDATE notes SET user_id = 1, created_at = NOW(), updated_at = NOW()"
    )

    op.alter_column('notes', 'user_id', nullable=False)
    op.alter_column('notes', 'created_at', nullable=False)
    op.alter_column('notes', 'updated_at', nullable=False)

    op.create_foreign_key(
        "fk_notes_user_id_users",
        "notes",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
    "fk_notes_user_id_users",
    "notes",
    type_="foreignkey"
    )
    op.drop_column('notes', 'updated_at')
    op.drop_column('notes', 'created_at')
    op.drop_column('notes', 'user_id')
    # ### end Alembic commands ###
